server:
  port: 8081
  servlet:
    jsp:
      init-parameters:
        development: true

spring:
  profiles:
    active: dev
  mvc:
    view:
      prefix: /
      suffix: .jsp

redis:
  #0关闭redis，1开启redis
  flag: 0

mybatis:
  mapper-locations: classpath:mapper/*.xml

version: 1.0.0
