server:
  port: 8080
  servlet:
    session:
      timeout: PT24H
    jsp:
      init-parameters:
        development: true

spring:
  profiles:
    active: dev
  mvc:
    view:
      prefix: /
      suffix: .jsp

redis:
  #0关闭redis，1开启redis
  flag: 0

version: 1.0.0
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.kkk.entity
