spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pay_manage?characterEncoding=utf8&amp;useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    url: 127.0.0.1
  freemarker:
    suffix: .ftl
